package controller

enum class StatusCodes {
  BAD_PORT_STRING,
  CONNECTION_MADE,
  SOCKET_CONNECTION_FAILED,
  OK,
  ERROR,
  SEND_GAME_CARD,
  RECEIVE_IMAGE,
  RECEIVE_STRING,
  SEARCH_GAME,
  FOUND_GAME,
  GAME_NOT_FOUND
}